<a href="https://colab.research.google.com/github/kvneswar/ml-nit/blob/master/02_numpy_practice_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np

# convert list to an array
arr = np.array([1, 2, 3])

print(type(arr))

arr = np.arange(0, 10) # generate an array with a range

print(arr)

arr = np.arange(0, 10, 2) # generate an array with a range with step

print(arr)

arr = np.ones(3, np.int32) # two dim array

print(arr)

arr = np.ones((3, 3), np.int32) # two dim array

print(arr)

arr = np.random.randint(0, 10)

print(arr)

arr = np.random.randint(0, 10, 5)

print(arr)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 1 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
9
[9 6 1 4 8]
